# Scans the media\ folder and (re)writes playlist.js with the files found,
# ordered by filename. Prefix files with 01_, 02_, 03_, 04_ (etc.) to control
# playback order, e.g.:
#   01_intro.mp4
#   02_demo.mp4
#   03_handout.pdf
#   04_closing.jpg

$mediaDir = Join-Path $PSScriptRoot "media"
$outFile  = Join-Path $PSScriptRoot "playlist.js"
$allowedExt = @(".mp4", ".webm", ".mov", ".mkv", ".m4v", ".pdf", ".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp")

if (-not (Test-Path $mediaDir)) {
    Write-Error "Media folder not found: $mediaDir"
    exit 1
}

$files = Get-ChildItem -Path $mediaDir -File |
    Where-Object { $allowedExt -contains $_.Extension.ToLower() } |
    Sort-Object Name

if ($files.Count -eq 0) {
    Write-Warning "No media files found in $mediaDir. Add your 2 videos, PDF, and image there first."
}

$lines = $files | ForEach-Object { "  " + ($_.Name | ConvertTo-Json) }
$body = $lines -join ",`n"

$content = @"
// Auto-generated by generate-playlist.ps1 -- do not edit by hand.
// Run generate-playlist.ps1 after adding/renaming files in the media\ folder.
const PLAYLIST = [
$body
];
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host "Wrote $($files.Count) file(s) to playlist.js:"
$files | ForEach-Object { Write-Host "  $($_.Name)" }
