// Auto-generated by generate-playlist.ps1 -- do not edit by hand.
// Run generate-playlist.ps1 after adding/renaming files in the media\ folder.
const PLAYLIST = [
  "03_Unified-Case-Management.pdf",
  "04_IACP-2.1-AI-Engineering-Highlight.png"
];
